<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('users')->delete();
        
        \DB::table('users')->insert(array (
            0 => 
            array (
                'company_email' => 'Hexaa User',
                'company_name' => 'Hexaa User',
                'created_at' => '2022-04-10 14:25:54',
                'email' => 'user@user.com',
                'email_verified_at' => NULL,
                'id' => 1,
                'is_logged_in' => 0,
                'name' => 'Hexaa User',
                'password' => '$2y$10$reD68HWVpfvbUKStd6aSUevtTNNKbfGeKFAQ1ieCka1nuUSMVQzzK',
                'phone' => '14124545',
                'remember_token' => NULL,
                'role_id' => 1,
                'updated_at' => '2022-04-10 14:25:54',
            ),
            1 => 
            array (
                'company_email' => 'naov Forwarder',
                'company_name' => 'forwarder@naov.com',
                'created_at' => '2022-04-10 14:29:46',
                'email' => NULL,
                'email_verified_at' => NULL,
                'id' => 2,
                'is_logged_in' => 0,
                'name' => NULL,
                'password' => NULL,
                'phone' => NULL,
                'remember_token' => NULL,
                'role_id' => 2,
                'updated_at' => '2022-04-10 14:29:46',
            ),
            2 => 
            array (
                'company_email' => 'forwarder@naov.com',
                'company_name' => 'Naov Forwarder',
                'created_at' => '2022-04-10 14:30:25',
                'email' => NULL,
                'email_verified_at' => NULL,
                'id' => 3,
                'is_logged_in' => 0,
                'name' => NULL,
                'password' => NULL,
                'phone' => NULL,
                'remember_token' => NULL,
                'role_id' => 2,
                'updated_at' => '2022-04-10 14:30:25',
            ),
            3 => 
            array (
                'company_email' => 'forwarder@naov.com',
                'company_name' => 'Naov Forwarder',
                'created_at' => '2022-04-10 14:33:40',
                'email' => NULL,
                'email_verified_at' => NULL,
                'id' => 4,
                'is_logged_in' => 0,
                'name' => NULL,
                'password' => NULL,
                'phone' => NULL,
                'remember_token' => NULL,
                'role_id' => 2,
                'updated_at' => '2022-04-10 14:33:40',
            ),
            4 => 
            array (
                'company_email' => 'forwarder2@naov.com',
                'company_name' => 'Naov Forwarder 2',
                'created_at' => '2022-04-10 14:33:55',
                'email' => NULL,
                'email_verified_at' => NULL,
                'id' => 5,
                'is_logged_in' => 0,
                'name' => NULL,
                'password' => NULL,
                'phone' => NULL,
                'remember_token' => NULL,
                'role_id' => 2,
                'updated_at' => '2022-04-10 14:33:55',
            ),
            5 => 
            array (
                'company_email' => 'forwarder3@naov.com',
                'company_name' => 'Naov Forwarder 3',
                'created_at' => '2022-04-10 14:34:06',
                'email' => NULL,
                'email_verified_at' => NULL,
                'id' => 6,
                'is_logged_in' => 0,
                'name' => NULL,
                'password' => NULL,
                'phone' => NULL,
                'remember_token' => NULL,
                'role_id' => 2,
                'updated_at' => '2022-04-10 14:34:06',
            ),
            6 => 
            array (
                'company_email' => 'forwarder4@naov.com',
                'company_name' => 'Naov Forwarder 4',
                'created_at' => '2022-04-10 14:34:20',
                'email' => NULL,
                'email_verified_at' => NULL,
                'id' => 7,
                'is_logged_in' => 0,
                'name' => NULL,
                'password' => NULL,
                'phone' => NULL,
                'remember_token' => NULL,
                'role_id' => 2,
                'updated_at' => '2022-04-10 14:34:20',
            ),
            7 => 
            array (
                'company_email' => 'forwarder5@naov.com',
                'company_name' => 'Naov',
                'created_at' => '2022-04-10 14:34:32',
                'email' => 'forwarder5@naov.com',
                'email_verified_at' => NULL,
                'id' => 8,
                'is_logged_in' => 0,
                'name' => 'forwarder',
                'password' => '$2y$10$TY02CbqQLpxUUi1BpBEjAO8fvWmiwe0WX1LTd3aJ73L3NDGQIMJ0e',
                'phone' => '14124545',
                'remember_token' => NULL,
                'role_id' => 2,
                'updated_at' => '2022-04-11 05:06:09',
            ),
            8 => 
            array (
                'company_email' => 'forwarder9@naov.com',
                'company_name' => 'Naov',
                'created_at' => '2022-04-11 04:40:13',
                'email' => 'forwarder9@naov.com',
                'email_verified_at' => NULL,
                'id' => 9,
                'is_logged_in' => 0,
                'name' => 'forwarder',
                'password' => '$2y$10$0RctZLaPTCXFu6VKL3V1PeTiUBZAbJrgaU4u52KoEImNajrM6B1QK',
                'phone' => '14124545',
                'remember_token' => NULL,
                'role_id' => 2,
                'updated_at' => '2022-04-11 04:40:13',
            ),
            9 => 
            array (
                'company_email' => 'test@gmail.com',
                'company_name' => 'Test',
                'created_at' => '2022-04-14 12:37:32',
                'email' => 'haris@gmail.com',
                'email_verified_at' => NULL,
                'id' => 10,
                'is_logged_in' => 0,
                'name' => 'Syed Haris',
                'password' => '$2y$10$CQeoc72dWXEHNZROlVArxeVZ7H6oryzuKAjGzHKPv5aHsBPWCSqVW',
                'phone' => '3365878784',
                'remember_token' => NULL,
                'role_id' => 3,
                'updated_at' => '2022-04-14 12:37:32',
            ),
            10 => 
            array (
                'company_email' => 'shipper@gmail.com',
                'company_name' => 'test',
                'created_at' => '2022-04-14 12:39:36',
                'email' => 'sheraz@gmail.com',
                'email_verified_at' => NULL,
                'id' => 11,
                'is_logged_in' => 0,
                'name' => 'Sheraz',
                'password' => '$2y$10$dEG9C/WTgJEOf4JTa5CKlOy85HiYpv.BXOJfzriXF1C8tzUaBeOlK',
                'phone' => '3123312312',
                'remember_token' => NULL,
                'role_id' => 3,
                'updated_at' => '2022-04-14 12:41:05',
            ),
            11 => 
            array (
                'company_email' => 'shipper1@gmail.com',
                'company_name' => 'test1',
                'created_at' => '2022-04-14 12:39:49',
                'email' => 'rasib@gmail.com',
                'email_verified_at' => NULL,
                'id' => 12,
                'is_logged_in' => 0,
                'name' => 'Rasib',
                'password' => '$2y$10$DUYOPic9GZYkGmdwE/Xpn.Umsb2iWwYiwtIMTyNqTFdyxhTzlgC1W',
                'phone' => '3123123223',
                'remember_token' => NULL,
                'role_id' => 3,
                'updated_at' => '2022-04-14 12:41:44',
            ),
            12 => 
            array (
                'company_email' => 'forwarder@gmail.com',
                'company_name' => 'Test',
                'created_at' => '2022-04-14 12:40:12',
                'email' => 'waseem@gmail.com',
                'email_verified_at' => NULL,
                'id' => 13,
                'is_logged_in' => 0,
                'name' => 'Waseem',
                'password' => '$2y$10$dIk.KLAtezHKN6eBQ.8sPOxCG5iH9OcNmOkx8xvEA.87.9xMdR8du',
                'phone' => '3123123421',
                'remember_token' => NULL,
                'role_id' => 2,
                'updated_at' => '2022-04-14 12:42:42',
            ),
            13 => 
            array (
                'company_email' => 'testforwarder@gmail.com',
                'company_name' => 'Forwarder',
                'created_at' => '2022-04-14 12:45:57',
                'email' => 'ali@gmail.com',
                'email_verified_at' => NULL,
                'id' => 14,
                'is_logged_in' => 0,
                'name' => 'Ali',
                'password' => '$2y$10$WV0iIe6dyoni1OtlzH58ze39eYpSlgHpl4AbLba9nmUhAb3v8RgtG',
                'phone' => '3123421234',
                'remember_token' => NULL,
                'role_id' => 2,
                'updated_at' => '2022-04-14 12:47:05',
            ),
            14 => 
            array (
                'company_email' => 'huzefacompany@gmail.com',
                'company_name' => 'Huzefa\'s Company',
                'created_at' => '2022-04-20 10:32:41',
                'email' => 'huzefa@gmail.com',
                'email_verified_at' => NULL,
                'id' => 15,
                'is_logged_in' => 0,
                'name' => 'Huzefa',
                'password' => '$2y$10$8LS7BxOXuJ.Hn4v6/Uo1BuPSrldSeOc6gDfWR7BGZ5WUM1iazJvqe',
                'phone' => '3658784784',
                'remember_token' => NULL,
                'role_id' => 3,
                'updated_at' => '2022-04-20 10:32:41',
            ),
            15 => 
            array (
                'company_email' => 'haseebcompany@gmail.com',
                'company_name' => 'Haseeb\'s Company',
                'created_at' => '2022-04-20 10:33:40',
                'email' => 'haseeb@gmail.com',
                'email_verified_at' => NULL,
                'id' => 16,
                'is_logged_in' => 0,
                'name' => 'Haseeb',
                'password' => '$2y$10$gHfdWzC1Bngv/xJ5mAtsgOQ1PTf10cDkHsK2i6gkntOi5y626pEEi',
                'phone' => '3154178987',
                'remember_token' => NULL,
                'role_id' => 3,
                'updated_at' => '2022-04-20 10:34:44',
            ),
            16 => 
            array (
                'company_email' => 'moizcompany@gmail.com',
                'company_name' => 'Moiz\'s Company',
                'created_at' => '2022-04-20 10:35:11',
                'email' => 'moiz@gmail.com',
                'email_verified_at' => NULL,
                'id' => 17,
                'is_logged_in' => 0,
                'name' => 'Moiz',
                'password' => '$2y$10$5PXzmpdhZcJK9SfaZPUSOuzx4T6R9xkL41hYeqnLSJDGuxvb.iFUq',
                'phone' => '3135478987',
                'remember_token' => NULL,
                'role_id' => 2,
                'updated_at' => '2022-04-20 10:36:28',
            ),
            17 => 
            array (
                'company_email' => 'danishcompnay@gmail.com',
                'company_name' => 'Danish\'s Company',
                'created_at' => '2022-04-20 10:36:54',
                'email' => 'danish@gmail.com',
                'email_verified_at' => NULL,
                'id' => 18,
                'is_logged_in' => 0,
                'name' => 'Danish',
                'password' => '$2y$10$C9gRnF2CoRcFAnfkDqpMNO.59PIy1gfkfu8SW2dn0q6KG89ORQaMW',
                'phone' => '3698578745',
                'remember_token' => NULL,
                'role_id' => 2,
                'updated_at' => '2022-04-20 10:38:17',
            ),
            18 => 
            array (
                'company_email' => 'acompany@gmail.com',
                'company_name' => 'A\'s Company',
                'created_at' => '2022-04-20 19:15:59',
                'email' => 'a@gmail.com',
                'email_verified_at' => NULL,
                'id' => 19,
                'is_logged_in' => 0,
                'name' => 'A',
                'password' => '$2y$10$N9YPuKm2fBMZ.sMUi7xlvOv8k2E5SKXUkh0/fE.uNvRdiXJqIXT.O',
                'phone' => '3658789874',
                'remember_token' => NULL,
                'role_id' => 3,
                'updated_at' => '2022-04-20 19:15:59',
            ),
            19 => 
            array (
                'company_email' => 'bcompany@gmail.com',
                'company_name' => 'B\'s Company',
                'created_at' => '2022-04-20 19:16:28',
                'email' => 'b@gmail.com',
                'email_verified_at' => NULL,
                'id' => 20,
                'is_logged_in' => 0,
                'name' => 'B',
                'password' => '$2y$10$S8xZjVZ8JNXmQXiHibQ7pOBLJwnuK1ScD1iYSsoess2u4OhCnK22q',
                'phone' => '3658784784',
                'remember_token' => NULL,
                'role_id' => 3,
                'updated_at' => '2022-04-20 19:17:25',
            ),
            20 => 
            array (
                'company_email' => 'ccompany@gmail.com',
                'company_name' => 'C\'s Company',
                'created_at' => '2022-04-20 19:17:45',
                'email' => 'c@gmail.com',
                'email_verified_at' => NULL,
                'id' => 21,
                'is_logged_in' => 0,
                'name' => 'C',
                'password' => '$2y$10$4zG3jc4bnCfCeM3OCBz.KuuZGt4HaoHyZ8k4fr0z4KVJfSpuA9iGm',
                'phone' => '3698784784',
                'remember_token' => NULL,
                'role_id' => 2,
                'updated_at' => '2022-04-20 19:19:06',
            ),
            21 => 
            array (
                'company_email' => 'dcompany@gmail.com',
                'company_name' => 'D\'s Company',
                'created_at' => '2022-04-20 19:19:23',
                'email' => 'd@gmail.com',
                'email_verified_at' => NULL,
                'id' => 22,
                'is_logged_in' => 0,
                'name' => 'D',
                'password' => '$2y$10$D8.DlPk54OD9oW2nCkJeIuj/TMEMyaUGnEtfegoY24gD1lMgjI8UO',
                'phone' => '3665878478',
                'remember_token' => NULL,
                'role_id' => 2,
                'updated_at' => '2022-04-20 19:20:47',
            ),
        ));
        
        
    }
}